# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'GAP Days Spring 2021'
tagline:          'The GAP Releases'
description:      '15<sup>th</sup> to 19<sup>th</sup> February 2021'
location:         'Virtual/Remote/Home Offices'
url:              https://www.gapdays.de
baseurl:          /gapdays2021-spring


exclude: [ "LICENSE.hyde.md", "README.hyde.md", "program.aux", "program.log", "program.out", "program.tex", "misc" ]
